[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
trusts = "arngwbKQjNF1q6s1NYURDPNQWHCQTfx5sdMQS9tB7ta"
[programs.devnet]
trusts = "arngwbKQjNF1q6s1NYURDPNQWHCQTfx5sdMQS9tB7ta"
[programs.mainnet]
trusts = "arngwbKQjNF1q6s1NYURDPNQWHCQTfx5sdMQS9tB7ta"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/joeymeere/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
